### ISSUE TITLE
USER STORY : (Customer) Log in 

### ISSUE THREAD

**Issue by rockroman** [rockroman/OOSE-Part2#3]
As a customer, I want to log in to my account so that I can access my purchase history, manage my profile, and track orders. 

## Acceptance Criteria
<ul>
    <li>When a user clicks on the "Register" link in the navbar, they should be directed to a register page where they are prompted to provide all necessary information to create a profile/account.</li>
     <li>Upon successful registration, the user's information and credentials should be securely saved to the database.</li>
     <li>Acceptance criteria 3</li>
</ul>

# Tasks
- [X] Create a "Register" and "Login" link in the navigation section of the garden center system.
- [X] Develop Register and Login forms that will prompt user to input all required info to create account
- [X] Implement functionality to securely save user information and credentials to the database upon successful registration
